# Generated by Django 2.2.14 on 2020-08-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(default='UNNC', max_length=30)),
                ('title', models.CharField(default='BSc Student', max_length=50)),
                ('Grade', models.CharField(default='4.00', max_length=5)),
                ('date_start', models.CharField(default='September 2010', max_length=100)),
                ('date_end', models.CharField(default='September 2010', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='experirence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experirence_title', models.TextField()),
                ('experirence_text', models.TextField()),
                ('experirence_date_start', models.CharField(default='September 2010', max_length=100)),
                ('experirence_date_end', models.CharField(default='September 2010', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=12),
        ),
    ]
