# Generated by Django 2.2.14 on 2020-08-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200806_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='facility',
            field=models.CharField(default='UNNC', max_length=100),
        ),
    ]
