# Generated by Django 2.2.14 on 2020-08-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200806_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Grade',
            field=models.CharField(default='4.00', max_length=100),
        ),
    ]
