# Generated by Django 2.2.14 on 2020-08-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200806_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='header_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
