# Generated by Django 2.2.15 on 2020-08-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200808_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='award',
        ),
        migrations.DeleteModel(
            name='education',
        ),
        migrations.DeleteModel(
            name='experience',
        ),
        migrations.DeleteModel(
            name='skills',
        ),
    ]
