# Generated by Django 2.2.15 on 2020-08-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200823_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_slide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
