# Generated by Django 2.2.15 on 2020-08-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(default='UNNC', max_length=100)),
                ('title', models.CharField(default='BSc Student', max_length=50)),
                ('Grade', models.CharField(default='4.00', max_length=100)),
                ('date_start', models.CharField(default='September 2010', max_length=100)),
                ('date_end', models.CharField(default='September 2010', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_title', models.TextField()),
                ('experience_text', models.TextField()),
                ('experience_date_start', models.CharField(default='September 2010', max_length=100)),
                ('experience_date_end', models.CharField(default='September 2010', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
