# Generated by Django 2.2.15 on 2020-08-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='experience_name',
            field=models.TextField(default='default'),
        ),
    ]
