# Generated by Django 2.2.15 on 2020-08-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_experience_experience_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_name',
            field=models.TextField(default='Intern'),
        ),
    ]
